### ISSUE TITLE
gaze control, homing, context

### ISSUE THREAD

**Issue by matejhof** [robotology/peripersonal-space#35]
These issues popped up during use of PPS in WYSIWYD (https://github.com/robotology/wysiwyd/issues/139#issuecomment-278668720)
It is about https://github.com/robotology/peripersonal-space/blob/master/modules/visuoTactileWrapper/vtWThread.cpp#L460

quoting the post of @pattacini:

These lines are wrong:

``` 
igaze ->lookAtAbsAngles(ang);
igaze ->restoreContext(contextGaze);
igaze ->stopControl(); 
```

Please correct them with:

```
igaze ->lookAtAbsAnglesSync(ang);
igaze ->waitMotionDone();
igaze ->restoreContext(contextGaze); 
```

Anyway, I wouldn't keep this homing. Further, the use of the context might be problematic and interfering with other modules.

General question
Why does PPS control the gaze changing the context? Shouldn't it just use the gaze interface to sense the posture?

@alecive  Do you have an idea, in particular regarding the context?

**Comment by alecive** [comment]
I don't really understand why you need my feedback on this, but anyway:

 > `igaze ->lookAtAbsAnglesSync(ang);`

I don't know what that is, is that a new method? If @pattacini says so, feel free to change it.

 > I wouldn't keep this homing. 

Feel free to comment it out. It's kind of nice for the robot to look straight when the module is closed, but it's not really important. I.e. I don't care :grimacing: 

> Further, the use of the context might be problematic and interfering with other modules.

The context is used explicitly to not interfere with other modules. For further info, please go here : http://wiki.icub.org/brain/icub_gaze_interface.html (section named Context Switch ) 
I need it mainly to be sure to have saccades disabled - see https://github.com/robotology/peripersonal-space/blob/master/modules/visuoTactileWrapper/vtWThread.cpp#L64 . Otherwise I think tracking would be kind of hard :grin: 

I don't know the context in which you're using the `vtWrapper`, so it's kind of hard to provide you with feedback on this. Closing here, answering in https://github.com/robotology/wysiwyd/issues/139

**Comment by pattacini** [comment]
The real problem is changing the context back while moving. That's it
